### ISSUE TITLE
学长name1e5s.fun的服务器好像崩了

### ISSUE THREAD

**Issue by evpeople** [name1e5s/WhereToSleep#2]
我打算自己部署一个，但是utils里的run_example运行了一个jwgl.py的文件，我在commit记录中没有找到。学校教务教室课表查询可以直接找到所有教室的课表，但是不能打印，能打印的各类课表查询又不能直接查询到所有教室的课表。。就卡在这了

**Comment by name1e5s** [comment]
看起来是 4514 端口不知道为什么出不去了 等我晚上处理一下。jwgl.py 的源码是当初一时兴起直接在服务器上糊的，所以一直没有同步到github上，晚上我找一下发上来。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: little camel ***@***.***&gt;
发送时间: 2021年12月15日 11:57
收件人: name1e5s/WhereToSleep ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [name1e5s/WhereToSleep] 学长name1e5s.fun的服务器好像崩了 (Issue #2)





 
我打算自己部署一个，但是utils里的run_example运行了一个jwgl.py的文件，我在commit记录中没有找到。学校教务教室课表查询可以直接找到所有教室的课表，但是不能打印，能打印的各类课表查询又不能直接查询到所有教室的课表。。就卡在这了
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by evpeople** [comment]
学长我测试了一下，4514端口可以telnet上去，我尝试了
```telnet name1e5s.fun 4514
Trying 60.205.156.150...
Connected to name1e5s.fun.
Escape character is '^]'.
^]

telnet>
GET /free_classrooms?week=16&day=5&time=10&time=11&time=12&time=13&time=14 HTTP/1.1
Connection closed by foreign host. 
```
去模拟HTTP请求，但是被拒绝了，然后我看前端发送的请求设置跨域策略是 strict-origin-when-cross-origin，于是我加上了
` Host https://where-to-sleep.name1e5s.com/ `并尝试了`name1e5s.fun:4514` 但是都被服务器关闭了连接，我猜想服务器是只接受HTTPS的连接的。

同时我通过HTTP访问了 name1e5s.fun 发现因为没有备案被阻断了，我猜测阿里云对于所有端口的数据包进行检测，走HTTP协议的一律被阻断掉。

倒霉教务自己手里有数据做的那个空教室查询由难用数据还不准，气死了。学长找到jwgl.py的文件了吗，我有一个备案过的域名可以用来部署

**Comment by name1e5s** [comment]
> 学长我测试了一下，4514端口可以telnet上去，我尝试了
> 
> ```
> Trying 60.205.156.150...
> Connected to name1e5s.fun.
> Escape character is '^]'.
> ^]
> 
> telnet>
> GET /free_classrooms?week=16&day=5&time=10&time=11&time=12&time=13&time=14 HTTP/1.1
> Connection closed by foreign host. 
> ```
> 
> 去模拟HTTP请求，但是被拒绝了，然后我看前端发送的请求设置跨域策略是 strict-origin-when-cross-origin，于是我加上了 `Host https://where-to-sleep.name1e5s.com/`并尝试了`name1e5s.fun:4514` 但是都被服务器关闭了连接，我猜想服务器是只接受HTTPS的连接的。
> 
> 同时我通过HTTP访问了 name1e5s.fun 发现因为没有备案被阻断了，我猜测阿里云对于所有端口的数据包进行检测，走HTTP协议的一律被阻断掉。
> 
> 倒霉教务自己手里有数据做的那个空教室查询由难用数据还不准，气死了。学长找到jwgl.py的文件了吗，我有一个备案过的域名可以用来部署

是的，所以我打算把数据全放到前端里了...今晚下班更（如果有精力的话）
jwgl.py 昨晚玩原神玩忘了，今晚见就放（

**Comment by evpeople** [comment]
谢谢学长，我自己也部署成功了，就是crontab 定时任务没能启动成功，真是麻烦你啦
